name: First Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
    paths-ignore:
      - '.github/workflows/*'

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
         - name: Print greeting
           run: |
               echo "Hello"
               echo "Hello Hello"
         - name: Print Name
           run: echo "Name"
    deploy:
       needs: test
       runs-on: ubuntu-latest
       steps:
         - name: Print greeting2
           run: echo "Hello2"
         - name: Print Name2
           run: echo "Name2"
         - name: Checkout code
           uses: actions/checkout@v2
         - name: Set up Python 3.10
           uses: actions/setup-python@v3
           with:
            python-version: "3.10"
         - name: Output GitHub Context
           run: echo "${{toJSON(github)}}"
    output-info:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
          - name: Output event details
            run: echo "${{ toJSON(github.event) }}"
           
           
         
    
