name: First Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
    paths-ignore:
      - '.github/workflows/*'

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
           - name: Print greeting
             id: print_greeting
             continue-on-error: true
             run: |
                 echo "Hello"
                 echo "Hello Hello"
           - name: Print Name
             id: print_name
             run: echo "Name"
           - name: Send Log         
             env:
              STEPS_CONTEXT: ${{ toJson(steps) }}
              JOB_CONTEXT: ${{ toJson(job) }}
              RUNNER_CONTEXT: ${{ toJson(runner) }}
              STRATEGY_CONTEXT: ${{ toJson(strategy) }}
              MATRIX_CONTEXT: ${{ toJson(matrix) }}
              RUN_NUMBER: ${{ toJson(github.run_number) }}
              RUN_ATTEMPT: ${{ toJson(github.run_attempt) }}
              RUN_JOB: ${{ toJson(github.job) }}
             run: |
                  YOUR_STRING='{"LOG":"OpenShift"}'
                  JSON_RESULT=$(echo "$YOUR_STRING" | jq -c '.')
                  LOG_DATA="{
                        \"STEP_STATUS\": \"$STEPS_CONTEXT\",
                        \"JOB\": \"$JOB_CONTEXT\",
                        \"RUNNER\": \"$RUNNER_CONTEXT\",
                        \"STRATEGY\": \"$STRATEGY_CONTEXT\",
                        \"MATRIX\": \"$MATRIX_CONTEXT\",
                        \"RUN_NUMBER\": \"$RUN_NUMBER\",
                        \"RUN_ATTEMPT\": \"$RUN_ATTEMPT\",
                        \"JOB_NAME\": \"$RUN_JOB\",
                        \"JSON_TEST\": \"$JSON_RESULT\",
                      }" 
                  echo "Logging data: $LOG_DATA"   
                  
    deploy:
       needs: test
       runs-on: ubuntu-latest
       steps:
         - name: Print greeting2
           run: echo "Greeting2" 
         - name: Print Name2
           id: print_name2
           run: echo "Name2"   
         - name: Checkout code
           id: check_out
           continue-on-error: true
           uses: actions/checkout@v2
         - name: Set up Python 3.10
           id: set-up-python
           continue-on-error: true
           uses: actions/setup-python@v3
           with:
            python-version: "3.10"
         - name: Send Log
           env:
              STEPS_CONTEXT: ${{ toJson(steps) }}
              JOB_CONTEXT: ${{ toJson(job) }}
              RUNNER_CONTEXT: ${{ toJson(runner) }}
              STRATEGY_CONTEXT: ${{ toJson(strategy) }}
              MATRIX_CONTEXT: ${{ toJson(matrix) }}
              RUN_NUMBER: ${{ toJson(github.run_number) }}
              RUN_ATTEMPT: ${{ toJson(github.run_attempt) }}
              RUN_JOB: ${{ toJson(github.job) }}
           run: |
                
                 LOG_DATA="{
                          \"STEP_STATUS\": \"$STEPS_CONTEXT\",
                          \"JOB\": \"$JOB_CONTEXT\",
                          \"RUNNER\": \"$RUNNER_CONTEXT\",
                          \"STRATEGY\": \"$STRATEGY_CONTEXT\",
                          \"MATRIX\": \"$MATRIX_CONTEXT\",
                          \"RUN_NUMBER\": \"$RUN_NUMBER\",
                          \"RUN_ATTEMPT\": \"$RUN_ATTEMPT\",
                          \"JOB_NAME\": \"$RUN_JOB\"
                        }" 
                  cho "Logging data: $LOG_DATA"  
         - name: Output GitHub Context
           if: failure() && steps.set-up-python.outcome == 'failure'
           run: echo "${{toJSON(github)}}"
    output-info:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
          - name: Output event details
            env:
              STEPS_CONTEXT: ${{ toJson(steps) }}
              JOB_CONTEXT: ${{ toJson(job) }}
              RUNNER_CONTEXT: ${{ toJson(runner) }}
              STRATEGY_CONTEXT: ${{ toJson(strategy) }}
              MATRIX_CONTEXT: ${{ toJson(matrix) }}
            run: echo "$STEPS_CONTEXT"+"$JOB_CONTEXT"+"$RUNNER_CONTEXT"+"$STRATEGY_CONTEXT"+"$MATRIX_CONTEXT" 
            
    fail-job:
         runs-on: ubuntu-latest
         if: failure()
         needs: [test,deploy]
         steps:
            - name: setEnv
              run: |
               echo "GITHUB_SHA_SHORT=ABC123456789" >> $GITHUB_ENV
            - name: CallOtherWorkflow    
              uses: ./.github/workflows/docker-image.yml
              with:
                    name: "Data"
         
    
