name: First Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
         - name: Print greeting
           run: |
               echo "Hello"
               echo "Hello Hello"
         - name: Print Name
           run: echo "Name"
    deploy:
       needs: test
       runs-on: ubuntu-latest
       steps:
         - name: Print greeting2
           run: echo "Hello2"
         - name: Print Name2
           run: echo "Name2"
         - name: Checkout code
           uses: actions/checkout@v2
         - name: Set up Python 3.10
           uses: actions/setup-python@v3
           with:
            python-version: "3.10"
           
         
    
