name: First Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types:
      - opened
    paths-ignore:
      - '.github/workflows/*'

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
           - name: Print greeting
             run: |
                 echo "Hello"
                 echo "Hello Hello"
           - name: Print Name
             run: echo "Name"
    deploy:
       needs: test
       runs-on: ubuntu-latest
       steps:
         - name: Print greeting2
           run: echo "Greeting2" 
         - name: Print Name2
           run: echo "Name2"   
         - name: Checkout code
           continue-on-error: true
           uses: actions/checkout@v2
         - name: Send Log         
           env:
            STEPS_CONTEXT: ${{ toJson(steps) }}
            JOB_CONTEXT: ${{ toJson(job) }}
            RUNNER_CONTEXT: ${{ toJson(runner) }}
            STRATEGY_CONTEXT: ${{ toJson(strategy) }}
            MATRIX_CONTEXT: ${{ toJson(matrix) }}
           run: echo "$STEPS_CONTEXT"+"$JOB_CONTEXT"+"$RUNNER_CONTEXT"+"$STRATEGY_CONTEXT"+"$MATRIX_CONTEXT"     
         - name: Set up Python 3.10
           id: set-up-python
           continue-on-error: true
           uses: actions/setup-python@v3
           with:
            python-version: "3.10"

         - name: Send Log         
           env:
            STEPS_CONTEXT: ${{ toJson(steps) }}
            JOB_CONTEXT: ${{ toJson(job) }}
            RUNNER_CONTEXT: ${{ toJson(runner) }}
            STRATEGY_CONTEXT: ${{ toJson(strategy) }}
            MATRIX_CONTEXT: ${{ toJson(matrix) }}
           run: echo "$STEPS_CONTEXT"+"$JOB_CONTEXT"+"$RUNNER_CONTEXT"+"$STRATEGY_CONTEXT"+"$MATRIX_CONTEXT"     
         - name: Output GitHub Context
           if: failure() && steps.set-up-python.outcome == 'failure'
           run: echo "${{toJSON(github)}}"
    output-info:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
          - name: Output event details
            env:
              STEPS_CONTEXT: ${{ toJson(steps) }}
              JOB_CONTEXT: ${{ toJson(jobs) }}
              RUNNER_CONTEXT: ${{ toJson(runner) }}
              STRATEGY_CONTEXT: ${{ toJson(strategy) }}
              MATRIX_CONTEXT: ${{ toJson(matrix) }}
            run: echo "$STEPS_CONTEXT"+"$JOB_CONTEXT"+"$RUNNER_CONTEXT"+"$STRATEGY_CONTEXT"+"$MATRIX_CONTEXT" 
            
    fail-job:
         if: failure()
         needs: [test,deploy]
         uses: ./.github/workflows/docker-image.yml
         
    
